name: Build and Run all Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: Install Dependencies
        run: npm ci
      - name: Audit Dependencies
        run: npm audit --omit dev
      - name: Lint
        run: npm run lint:nofix
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:nowatch